### PR TITLE
Lockwise rebrand

### PR DESCRIPTION
**Pull request by devinreams**
In progress for the rebranding tracked at #114 

**To be completed:**
- [x] Fix background SVG to match spec
- [x] Replace link with button & subheader for add-on
- [x] replace FAQ imagery for old app screens
  - [x] replace [autofill-settings-android](https://github.com/mozilla-lockwise/mozilla-lockwise.github.io/pull/117#issuecomment-495456565)
  - https://zpl.io/VQvAXQx
  - https://zpl.io/VDAkJgr
- [x] sizing of Lockwise logo on detail screens is pretty small compared to what exists today (FAQ) 
- [x] it would be nice to have the entire footer fixed to the base of the view port, as currently if someone is on a small or medium height screen, they may not see the navigation links in the footer. 
- [x] add favicon

Home:

image

FAQ:
image

Mobile:
image

Built off the branch at #116

### CODE REVIEW

**Comment by devinreams** [comment]
Work in Progress preview @changecourse @sandysage 

Screen Shot 2019-05-13 at 2 33 44 PM
Screen Shot 2019-05-13 at 2 33 46 PM

**Comment by sandysage** [comment]
This is the latest I have from @changecourse for what the May 28th layout/design needs to be for the splash page:
Lockwise Web (3)

The FAQ / internal pages look great to me, but I'll defer to Ryan if changes are needed.

**Comment by devinreams** [comment]
Ryan has updated above with requested changes.

@changecourse I may not be able to accomplish all these but will do a best effort. how are your CSS chops? 😏

**Comment by devinreams** [comment]
@changecourse for the FAQ updates, I think we still need one updated `autofill-settings-android` image:

Autofill_FAQ_-_Lockwise_– Web_-_Zeplin

**Comment by devinreams** [comment]
Here's how everything looks now:

Home:
image


FAQ:
image

Mobile:
image


I'm not super familiar with flex box so I think I've done as best I can to get the 3 buttons spaced and aligned and _kinda_ centered to match the mocks, but struggled to get pixel perfect since we're dealing in percentages and stuff. 🤷‍♂

**Comment by devinreams** [comment]
>I updated the Zeplin file to contain the new screenshot for Android autofill provider.

Done!

>It looks like the background SVG is still not rendering properly with the blending modes, but certainly not a dealbreaker... I can bug JGruen about how he did it previously later.

Oh I just dropped in the SVG in as exported from Zeplin.

Looking at the diff, I see a `style="mix-blend-mode:overlay"` on elipse and circle that's in the old but not the new SVG.

https://github.com/mozilla-lockwise/mozilla-lockwise.github.io/pull/117/files#diff-9b2357fffe7f7da8670d38d4b2347592

>I'm curious, if the footer is now fixed, does it need a white bg for instances where it may overlap with the devices?

Yeah I thought about that too and forgot to mention it, good call out.

---

Here's how everything looks now with the SVG blending and white footer on three screen sizes:


image
Screen Shot 2019-05-24 at 9 06 10 AM
Screen Shot 2019-05-24 at 9 06 56 AM

**Comment by devinreams** [comment]
@changecourse and while we're at it, do we want the Lockwise logo instead of the Firefox logo as the favicon in the address bar/tabs?

**Comment by changecourse** [comment]
[Glpyh.svg.zip](https://github.com/mozilla-lockwise/mozilla-lockwise.github.io/files/3217592/Glpyh.svg.zip)

**Comment by devinreams** [comment]
Final version with a PNG instead of SVG for background and a revised favicon:

image

**Pull request merged**
